export type MetricStatus = "reported" | "scope";

export type ProjectMetric = {
  value: string;
  label: string;
  context: string;
  status: MetricStatus;
};

export type MediaKind = "image" | "video" | "gif";

export type ProjectImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  title: string;
  caption: string;
  treatment: "device" | "composition" | "edge" | "photo" | "overview" | "paper";
  kind?: MediaKind;
  poster?: string;
  chapter?: string;
  half?: boolean;
  span?: "half" | "third" | "quarter";
  loop?: boolean;
  inset?: boolean;
  wash?: boolean;
  placeholder?: boolean;
  placeholderHint?: string;
  src2x?: string;
};

export type Project = {
  slug: string;
  company: string;
  name: string;
  shortName: string;
  headline: string;
  intro: string;
  capabilities: string;
  theme: string;
  year: string;
  outcomes?: ProjectMetric[];
  resultNote?: string;
  problem?: string;
  made?: string;
  role: string;
  gallery: ProjectImage[];
  /** Omit from nav, next-project chain, and static routes when true. */
  hidden?: boolean;
};

export const projects: Project[] = [
  {
    slug: "oats-overnight-app",
    company: "Oats Overnight",
    name: "The customer app",
    shortName: "Oats App",
    headline: "Easier orders. More reasons to stay.",
    intro:
      "A subscription experience built to help customers help themselves — and give the business more room to grow.",
    capabilities: "Customer experience · Ecommerce · Retention",
    theme: "oats",
    year: "2023–",
    outcomes: [
      {
        value: "~$50k",
        label: "additional monthly sales",
        context: "Reported after the initial app redesign.",
        status: "reported",
      },
      {
        value: "~15%",
        label: "fewer cancellations",
        context: "The app contributed to the reduction.",
        status: "reported",
      },
      {
        value: "+50%",
        label: "monthly logins",
        context: "From 30,000 to 45,000 after the redesign.",
        status: "reported",
      },
    ],
    resultNote:
      "Results reported in the original case study, across the broader product team’s work. Figures reflect the periods described there.",
    problem: "Simple subscription changes were becoming support tickets.",
    made: "I rebuilt the everyday jobs — manage an order, choose flavors, and keep a subscription that fits.",
    role: "Tyler led product design, research, and the Oaty design system, working with Oats Overnight’s engineering and business teams.",
    gallery: [
      {
        src: "/work/oats-dashboard.webp",
        width: 579,
        height: 1092,
        alt: "Oats Overnight flavor builder, ratings, dashboard, Protein Coffee, and referrals",
        title: "One app. The whole customer relationship.",
        caption: "Ordering, discovery, feedback, and referrals in one familiar experience.",
        treatment: "overview",
      },
      {
        src: "/work/oats-before-after.mp4",
        width: 2388,
        height: 2358,
        alt: "Side-by-side of the first app release and the September 2023 rebuild",
        title: "First release. Then the rebuild.",
        caption: "The inherited app on the left. The rebuilt experience on the right.",
        treatment: "edge",
        kind: "video",
        poster: "/work/oats-before-after-poster.webp",
      },
      {
        src: "/work/oats-shop-motion.mp4",
        width: 1942,
        height: 1594,
        alt: "New flavor, Protein Coffee, and shop opportunities in the rebuilt app",
        title: "Room to buy again.",
        caption: "New flavors and products sit next to the next delivery.",
        treatment: "edge",
        kind: "video",
        poster: "/work/oats-shop-motion-poster.webp",
        loop: true,
        chapter: "Make everyday ordering easier",
      },
      {
        src: "/work/oats-shop-cards.webp",
        width: 2000,
        height: 759,
        alt: "Oats Overnight new flavor announcement, Protein Coffee offer, and shopping categories",
        title: "The offers, in place.",
        caption: "Announcement, new product, and shop — without leaving the portal.",
        treatment: "edge",
      },
      {
        src: "/work/oats-order-management.webp",
        width: 1302,
        height: 1074,
        alt: "Skip, delay, and shipping actions on the subscription home",
        title: "The three actions people actually need.",
        caption: "Skip, delay, and ship — one tap away.",
        treatment: "paper",
        half: true,
      },
      {
        src: "/work/oats-dashboard-loop.mp4",
        width: 580,
        height: 1094,
        alt: "The rebuilt Oats Overnight home dashboard in motion",
        title: "The home, in motion.",
        caption: "Next order, shop, and loyalty in one place.",
        treatment: "device",
        kind: "video",
        poster: "/work/oats-dashboard.webp",
        loop: true,
        half: true,
      },
      {
        src: "/work/oats-flavor-builder.webp",
        width: 579,
        height: 1032,
        alt: "Oats Overnight flavor selection, nutrition, reviews, and bundle quantities",
        title: "Build the next box.",
        caption: "Flavors, reviews, and quantities together.",
        treatment: "device",
        half: true,
      },
      {
        src: "/work/oats-protein-coffee.webp",
        width: 579,
        height: 1032,
        alt: "Protein Coffee ordering with quantities and free gifts",
        title: "Make room for something new.",
        caption: "The same system, now for Protein Coffee.",
        treatment: "device",
        half: true,
      },
      {
        src: "/work/oats-loyalty.mp4",
        width: 1920,
        height: 1404,
        alt: "Loyalty walkthrough showing the updated homepage, loyalty tab, and reward progression",
        title: "Loyalty throughout the experience.",
        caption: "Home, rewards, and progression in one loop.",
        treatment: "edge",
        kind: "video",
        poster: "/work/oats-loyalty-poster.webp",
        chapter: "Build reasons to come back",
      },
      {
        src: "/work/oats-survey.mp4",
        width: 780,
        height: 1698,
        alt: "In-app flavor development survey walkthrough",
        title: "Give customers a voice.",
        caption: "A custom survey brings flavor feedback into the app.",
        treatment: "device",
        kind: "video",
        poster: "/work/oats-survey-poster.webp",
        half: true,
      },
      {
        src: "/work/oats-referrals.webp",
        width: 579,
        height: 1032,
        alt: "Referral sharing, reward progress, and referral activity",
        title: "Turn enthusiasm into referrals.",
        caption: "A simple invitation, with the next reward in view.",
        treatment: "device",
        half: true,
      },
      {
        src: "/work/oats-ratings.mp4",
        width: 1920,
        height: 1080,
        alt: "Ratings and notes interactions, including the later loyalty integration",
        title: "From personal notes to rewarded feedback.",
        caption: "Personal notes, then loyalty rewards.",
        treatment: "edge",
        kind: "video",
        poster: "/work/oats-ratings-poster.webp",
      },
      {
        src: "/work/oats-design-system.webp",
        width: 2048,
        height: 985,
        alt: "Oaty design system covering colors, type, components, and interface patterns",
        title: "Oaty: a foundation for what comes next.",
        caption: "Shared components, tokens, and docs for design and engineering.",
        treatment: "paper",
        chapter: "Give the product room to grow",
      },
    ],
  },
  {
    slug: "flavor-ratings",
    company: "Oats Overnight",
    name: "Flavor Ratings",
    shortName: "Ratings",
    headline: "Customer favorites. Business insight.",
    intro:
      "A useful little habit became a direct connection between what customers love and what the business makes next.",
    capabilities: "Customer insight · Product design · Loyalty",
    theme: "ratings",
    year: "2023–",
    outcomes: [
      {
        value: "80%+",
        label: "of purchases rated by habitual raters",
        context: "An engaged customer cohort, not all customers.",
        status: "reported",
      },
      {
        value: "+58%",
        label: "participation across two feedback tools",
        context: "Ratings & Notes and the Flavor in Development survey, together.",
        status: "reported",
      },
      {
        value: "45+",
        label: "flavors to keep track of",
        context: "The range customers navigated at the start of the project.",
        status: "scope",
      },
    ],
    resultNote:
      "The ratings cohort is described in the original project. The combined participation result is reported in the broader Oats app case study.",
    problem: "Customers already rated flavors — in spreadsheets, notes, and group posts. The business couldn’t see any of it.",
    made: "Star ratings and autosaving notes in the app. Later, the same habit earned loyalty rewards.",
    role: "Tyler led research, concept, interaction design, and testing, collaborating with the Oats Overnight team to ship and evolve the feature.",
    gallery: [
      {
        src: "/work/ratings-customer-research.webp",
        width: 2048,
        height: 1413,
        alt: "Customer-created spreadsheets, lists, and notes for remembering favorite flavors",
        title: "Start with what people already do.",
        caption: "Homemade charts and notes shaped the tool.",
        treatment: "paper",
      },
      {
        src: "/work/ratings-ui.mp4",
        width: 798,
        height: 1528,
        alt: "Fast star-rating interaction on a flavor list",
        title: "Rate.",
        caption: "Playful, not a survey.",
        treatment: "device",
        kind: "video",
        poster: "/work/ratings-ui-poster.webp",
        loop: true,
        span: "third",
        chapter: "The habit",
      },
      {
        src: "/work/ratings-notes.mp4",
        width: 798,
        height: 1528,
        alt: "Autosaving personal notes on a flavor",
        title: "Note.",
        caption: "Prep tweaks, saved as you type.",
        treatment: "device",
        kind: "video",
        poster: "/work/ratings-notes-poster.webp",
        loop: true,
        span: "third",
      },
      {
        src: "/work/ratings-loyalty.mp4",
        width: 798,
        height: 1528,
        alt: "Ratings earning loyalty points and rewards",
        title: "Earn.",
        caption: "Feedback that pays back.",
        treatment: "device",
        kind: "video",
        poster: "/work/ratings-loyalty-poster.webp",
        loop: true,
        span: "third",
      },
      {
        src: "/work/ratings-components.webp",
        width: 2000,
        height: 1138,
        alt: "Rating controls, flavor badges, category switching, and sorting options",
        title: "The details.",
        caption: "Stars, notes, and favorites-first sorting.",
        treatment: "paper",
      },
      {
        src: "/work/ratings-phone-photo.webp",
        width: 1536,
        height: 1024,
        alt: "A customer holding a phone displaying flavor ratings and notes",
        title: "An everyday habit.",
        caption: "Quick enough to use while the preference is still fresh.",
        treatment: "photo",
      },
      {
        src: "/work/oats-ratings.mp4",
        width: 1920,
        height: 1080,
        alt: "Flavor ratings, autosaving personal notes, and the later loyalty rewards integration",
        title: "The whole loop.",
        caption: "From personal notes to loyalty rewards.",
        treatment: "edge",
        kind: "video",
        poster: "/work/oats-ratings-poster.webp",
      },
    ],
  },
  {
    slug: "creativeos",
    company: "Independent",
    name: "creativeOS",
    shortName: "creativeOS",
    headline: "A creative studio that compounds.",
    intro:
      "I designed and built an AI-powered design studio solo — from brief to prototype to editable Figma handoff. The home chat is purpose-built for structured strategy: inline question cards, a highlight-and-clarify layer I designed, and research plus behavioral data that lands while you keep working. Today it powers concepting and retention design for Oats Overnight’s lean team.",
    capabilities: "Product design · AI systems · Design ops · Solo build",
    theme: "creativeos",
    year: "2026",
    outcomes: [
      {
        value: "Solo",
        label: "designer and builder",
        context: "Chat and critique interaction design, IA, agent orchestration, sync, and Figma bridge.",
        status: "scope",
      },
      {
        value: "2-way",
        label: "Figma bridge",
        context: "Push editable frames with rationale; pull craft back into the critique loop.",
        status: "scope",
      },
      {
        value: "Local-first",
        label: "multiplayer studio",
        context: "Attributed critique, git sync, and presence — without moving credentials to the cloud.",
        status: "scope",
      },
    ],
    resultNote:
      "creativeOS is in daily use on Oats Overnight design work. Figures describe scope and architecture, not revenue. The story is told through the product UI below.",
    problem:
      "Most creative tools reset every session. Briefs stay vague, feedback lives in docs, and senior judgment does not scale past one person’s attention. A growing design org needed a studio that remembers the rules, grounds work in real behavior, and hands off polish to Figma without losing the why.",
    made:
      "I built a local-first studio you brief like a sharp designer: the home chat renders Questions and Research as real UI—not markdown dumps—and a ChatCritique highlight menu keeps Pin, Clarify, and Comment marks on the source text. Competitive and Amplitude work runs in parallel with the thread so design is not blocked on separate research tickets. From there, conversation becomes a scored brief, six directions generate, Figma-style critique and rework run on the HTML, and verified editable layers push to Figma—with memory, design-system self-check, and attributed multiplayer throughout.",
    role: "Tyler designed and engineered creativeOS end to end — product strategy, interface, specialist agents, Express server, generation and critique pipelines, git-based multiplayer, Windows onboarding, and the Klaviyo email builder and Amplitude-informed briefs inside it.",
    gallery: [
      {
        src: "/work/creativeos-portrait.mp4",
        width: 1080,
        height: 1440,
        alt: "creativeOS interface in a vertical product walkthrough",
        title: "The studio, in motion.",
        caption: "Strategy, prototypes, critique, and handoff in one environment.",
        treatment: "edge",
        kind: "video",
        poster: "/work/creativeos-portrait-poster.webp",
        chapter: "The studio, in motion",
      },
      {
        src: "/work/creativeos-wide.mp4",
        width: 1600,
        height: 956,
        alt: "creativeOS workspace showing collaborative creative tools",
        title: "One room for the whole loop.",
        caption: "From first chat to shared critique — built for a small design org, not a demo.",
        treatment: "edge",
        kind: "video",
        poster: "/work/creativeos-wide-poster.webp",
      },
      {
        src: "/work/creativeos-chat-strategy.mp4",
        width: 1920,
        height: 1080,
        alt: "Placeholder for home chat with questions card and competitive research",
        title: "Thinking first. Homework in parallel.",
        caption:
          "The chat surfaces a few focused questions as inline fields—not a wall of markdown. Competitive precedent and product data pull in the background so you are not waiting on research or analytics to move.",
        treatment: "edge",
        kind: "video",
        placeholder: true,
        placeholderHint:
          "Screen recording or screenshot: home chat with Questions card (unanswered) + Research / Competitive analysis block in the thread; optional inset of project view Amplitude findings with staleness badge.",
        chapter: "Chat that pushes thinking",
      },
      {
        src: "/work/creativeos-chat-highlight.webp",
        width: 1600,
        height: 1000,
        alt: "Placeholder for highlight selection menu on assistant chat text",
        title: "I designed the clarify layer.",
        caption:
          "When output hand-waves or data needs a second read, you mark the exact words—Pin, Clarify, Comment—not a vague reply. The popover is the UI; the thread stays legible for you and teammates.",
        treatment: "edge",
        placeholder: true,
        placeholderHint:
          "Screenshot: text selected on an assistant message with reaction menu open (Pin / Drop / Push / Clarify / Comment).",
        chapter: "Highlight, clarify, send once",
      },
      {
        src: "/work/creativeos-chat-marks.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for persistent chat marks and bundled send",
        title: "Marks stay. One send.",
        caption:
          "Highlights and initials stay on the passage after reload. Answers and queued comments ship together—Send answers + N comments—in one turn.",
        treatment: "paper",
        half: true,
        placeholder: true,
        placeholderHint:
          "Screenshot: assistant bubble with yellow chat-mark highlights and initials + Questions card or send pill showing Send answers + N comments →.",
      },
      {
        src: "/work/creativeos-brief.webp",
        width: 1600,
        height: 1000,
        alt: "Placeholder for chat becoming a structured project brief",
        title: "Talk first. The brief follows.",
        caption: "The first message creates the project, files the thread, and shapes a PRD from the conversation.",
        treatment: "paper",
        placeholder: true,
        placeholderHint:
          "Screenshot: New Chat → first send → project appears in the sidebar with a structured brief on the project page.",
        chapter: "Brief the studio, not a blank page",
      },
      {
        src: "/work/creativeos-brief-quality.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for brief quality scoring and gut-check UI",
        title: "Pressure-test before pixels.",
        caption: "Weak audience, fuzzy success metrics, and solution-first asks get named with concrete fixes — every time.",
        treatment: "paper",
        placeholder: true,
        placeholderHint:
          "Screenshot: brief quality callouts or pre-ship gut check (weakest part / what to cut / what to bet on).",
        chapter: "Pressure-test before pixels",
      },
      {
        src: "/work/creativeos-generate.mp4",
        width: 1920,
        height: 1080,
        alt: "Placeholder for prototype generation on the canvas",
        title: "Six directions. Two bets.",
        caption: "Three by-the-book and three pushing-it options land progressively — grounded in the live design system and portal kit.",
        treatment: "edge",
        kind: "video",
        placeholder: true,
        placeholderHint:
          "Screen recording: generate prototypes → cards appear one-by-one → By the Book / Pushing It sections on the canvas.",
        chapter: "Six directions, two strategic bets",
      },
      {
        src: "/work/creativeos-critique.webp",
        width: 1600,
        height: 1000,
        alt: "Placeholder for Figma-style critique on a prototype",
        title: "Critique on the work.",
        caption: "Comment mode with element targeting and screen-scoped notes — not a paragraph in a doc.",
        treatment: "edge",
        placeholder: true,
        placeholderHint:
          "Screenshot or clip: full-preview overlay in Comment mode with a drawn region or element highlight and note composer.",
        chapter: "Critique on the work, not in a doc",
      },
      {
        src: "/work/creativeos-rework.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for apply comments and rework on one prototype",
        title: "Rework one direction.",
        caption: "Apply comments and rework rebuilds that file from its HTML with your words baked in — and a one-line changelog on the card.",
        treatment: "paper",
        placeholder: true,
        placeholderHint:
          "Screenshot: prototype card with Apply comments and rework + changelog badge (Revision of…).",
        chapter: "Rework one direction, keep the rest",
      },
      {
        src: "/work/creativeos-figma-push.webp",
        width: 1600,
        height: 1000,
        alt: "Placeholder for Push to Figma flow",
        title: "Editable handoff.",
        caption: "Push to Figma rebuilds native layers, binds design tokens, and adds a rationale card — verified editable before it counts as done.",
        treatment: "edge",
        placeholder: true,
        placeholderHint:
          "Screenshot: Push to Figma sheet + resulting Figma page (Round N, sections, rationale text beside frames).",
        chapter: "Hand off editable work to Figma",
      },
      {
        src: "/work/creativeos-figma-pull.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for import from Figma and version lineage",
        title: "Pull craft back in.",
        caption: "Figma edits return as a new version of the same direction — lineage intact, ready to critique again.",
        treatment: "paper",
        half: true,
        placeholder: true,
        placeholderHint: "Screenshot: Import from Figma modal or card badge ⇠ Pulled from Figma · vN.",
      },
      {
        src: "/work/creativeos-critique-ledger.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for critique ledger showing open vs addressed items",
        title: "What’s still open.",
        caption: "The critique ledger rolls up by direction — open feedback first, not a wall of cycle history.",
        treatment: "paper",
        half: true,
        placeholder: true,
        placeholderHint: "Screenshot: Critique Log / ledger view with open rows expanded and addressed items collapsed.",
      },
      {
        src: "/work/creativeos-memory.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for commit to memory and standing rules",
        title: "Corrections become rules.",
        caption: "Say commit to memory in a critique note — the studio stages it, promotes it, and every future direction has to respect it.",
        treatment: "paper",
        placeholder: true,
        placeholderHint:
          "Screenshot: critique note with commit to memory + pending memory queue or standing rules on the project.",
        chapter: "It remembers what you teach it",
      },
      {
        src: "/work/creativeos-multiplayer.webp",
        width: 1920,
        height: 1080,
        alt: "Placeholder for multiplayer attribution and sync",
        title: "Built for a real team.",
        caption: "Per-person critique shards, avatars on notes, sync status, and activity — agency with recourse, not an approval queue.",
        treatment: "edge",
        placeholder: true,
        placeholderHint:
          "Screenshot: two authors on critique cards, chat attribution, and sync pill / contributors panel.",
        chapter: "Built for a real team",
      },
      {
        src: "/work/creativeos-email.webp",
        width: 1600,
        height: 900,
        alt: "Placeholder for Klaviyo email builder output",
        title: "Email that cannot miss the bar.",
        caption: "Governed blocks, brand tokens, and hard checks before approval — on-brand and technically correct by construction.",
        treatment: "paper",
        placeholder: true,
        placeholderHint: "Screenshot: email builder form + generated Klaviyo-ready HTML preview.",
        chapter: "Email and governance",
      },
    ],
  },
  {
    slug: "coco-ai",
    hidden: true,
    company: "Teladoc Health",
    name: "Coco AI",
    shortName: "Coco AI",
    headline: "Healthcare guidance, with bedside manner.",
    intro:
      "A virtual healthcare assistant designed to feel calm, present, and useful — helping people ask simple questions and take the next step.",
    capabilities: "AI · Product design · Healthcare",
    theme: "coco",
    year: "2021",
    outcomes: [
      {
        value: "1",
        label: "living persona",
        context: "A single assistant for voice and text.",
        status: "scope",
      },
      {
        value: "3",
        label: "states with a job",
        context: "Idle, listening, and thinking — each with its own motion.",
        status: "scope",
      },
      {
        value: "Next step",
        label: "after every question",
        context: "Suggested actions, not just answers.",
        status: "scope",
      },
    ],
    resultNote:
      "To comply with a non-disclosure agreement, confidential information is omitted or obfuscated. The views here are Tyler’s and do not necessarily reflect those of Teladoc Health.",
    problem:
      "Healthcare is a lot to hold: treatment plans, appointments, medicine, messages. Patients needed a way to ask for help in plain language — without the product feeling cold or clever.",
    made: "I designed Coco as a living persona: always slightly in motion, with a bedside manner shaped by research. Idle, listening, and thinking each have a job. Suggested actions turn a question into the next useful step.",
    role: "Tyler designed the persona, interface, interactions, and prototypes, and partnered with research, engineering, and data on early builds.",
    gallery: [
      {
        src: "/home/coco-orb.mp4",
        width: 600,
        height: 600,
        alt: "Coco, a softly moving spherical healthcare assistant",
        title: "Alive, and ready to help.",
        caption: "Constant, subtle movement keeps Coco from feeling like a static icon.",
        treatment: "composition",
        kind: "video",
        poster: "/home/coco-orb-poster.webp",
        loop: true,
      },
      {
        src: "/work/coco-hero.mp4",
        width: 1440,
        height: 1440,
        alt: "Coco offering to help prepare for an upcoming doctor appointment",
        title: "A considered first moment.",
        caption: "Help arrives as a suggestion, not a command.",
        treatment: "edge",
        kind: "video",
        poster: "/work/coco-hero-poster.webp",
      },
      {
        src: "/work/coco-logo-from.webp",
        width: 2048,
        height: 348,
        alt: "Teladoc Health logo mark used as the starting point for Coco",
        title: "From the mark.",
        caption: "Coco’s form comes from deconstructing the Teladoc logo.",
        treatment: "paper",
        chapter: "Who do I want taking care of me?",
        half: true,
      },
      {
        src: "/work/coco-logo-to.webp",
        width: 2048,
        height: 279,
        alt: "Coco product mark derived from the Teladoc logo",
        title: "To a persona.",
        caption: "A product logo that can live in the interface, not just on a slide.",
        treatment: "paper",
        half: true,
      },
      {
        src: "/work/coco-idle.webp",
        width: 1608,
        height: 808,
        alt: "Coco idle state, gently hovering",
        title: "Idle.",
        caption: "A slow hover says Coco is attentive, not waiting to be woken up.",
        treatment: "paper",
        chapter: "How do I want to be taken care of?",
      },
      {
        src: "/work/coco-tap.webp",
        width: 1608,
        height: 808,
        alt: "Coco expanding toward the user when tapped",
        title: "Listening.",
        caption: "On tap, Coco expands slightly and begins to listen.",
        treatment: "paper",
        half: true,
      },
      {
        src: "/work/coco-think.webp",
        width: 1480,
        height: 808,
        alt: "Coco thinking state with a soft expanding glow",
        title: "Thinking.",
        caption: "The outer glow expands and contracts while a request is processed.",
        treatment: "paper",
        half: true,
      },
      {
        src: "/work/coco-phone-1.webp",
        width: 1311,
        height: 2622,
        alt: "Mobile conversation with Coco suggesting a helpful next action",
        title: "Ask a simple question.",
        caption: "“When is my next appointment?” should return a clear answer — and a next step.",
        treatment: "device",
        chapter: "Validating the useful parts",
        half: true,
      },
      {
        src: "/work/coco-phone-2.webp",
        width: 1261,
        height: 2522,
        alt: "Coco highlighting dates and actions from a care conversation",
        title: "Then offer the next action.",
        caption: "Dates, locations, and instructions become something the patient can act on.",
        treatment: "device",
        half: true,
      },
      {
        src: "/work/coco-voice.mp4",
        width: 576,
        height: 576,
        alt: "Prototype of Coco reacting while speaking with a patient",
        title: "Voice, not just type.",
        caption: "An early prototype of Coco reacting while speaking.",
        treatment: "composition",
        kind: "video",
        poster: "/work/coco-voice-poster.webp",
        loop: true,
      },
    ],
  },
  {
    slug: "teladoc-health",
    company: "Teladoc Health",
    name: "A more connected care experience",
    shortName: "Teladoc",
    headline: "One brand. A clearer path to care.",
    intro:
      "Turning a complex healthcare ecosystem into a more consistent experience, from choosing care to understanding the details.",
    capabilities: "Brand experience · Product design · Design systems",
    theme: "teladoc",
    year: "2021",
    outcomes: [
      {
        value: "1",
        label: "shared product language",
        context: "Connected care cards, icons, and interaction patterns.",
        status: "scope",
      },
      {
        value: "9 months",
        label: "of focused product work",
        context: "Project OneApp: brand expression, components, icons, and motion.",
        status: "scope",
      },
      {
        value: "AA / AAA",
        label: "contrast on the icon system",
        context: "Line weight and color tested for healthcare accessibility.",
        status: "scope",
      },
    ],
    resultNote:
      "Project OneApp · Brand expression, product details, and reusable visual systems. Illustration exploration and sketches by Tyler; an independent illustrator produced the final artwork.",
    problem:
      "Multiple acquisitions had left Teladoc with disconnected product experiences. The new brand needed to work where trust is earned: helping people understand their options and take the next step.",
    made: "I shaped the illustration direction, audited key components, explored launch and refresh motion, and built a consistent icon system for the new OneApp experience.",
    role: "Tyler contributed product design and visual systems within Teladoc’s wider OneApp team. Illustration work included exploration and sketches; an independent illustrator created the production artwork.",
    gallery: [
      {
        src: "/work/teladoc-app-overview.webp",
        width: 867,
        height: 1024,
        alt: "Five Teladoc product screens with a shared brand and care experience",
        title: "A shared identity across care.",
        caption: "Project OneApp brought fragmented experiences into one product language.",
        treatment: "composition",
      },
      {
        src: "/work/teladoc-illustration-exploration.webp",
        width: 2048,
        height: 1190,
        alt: "A meditation concept explored through different illustration styles in the Teladoc interface",
        title: "Find the right expression.",
        caption: "One concept, explored across styles to compare warmth, tone, and clarity.",
        treatment: "paper",
        chapter: "01 / A more human illustration system",
      },
      {
        src: "/work/teladoc-illustration-sketches.webp",
        width: 2400,
        height: 786,
        alt: "Continuous-line illustration sketches exploring human connection and healthcare",
        title: "Connection, drawn into the system.",
        caption:
          "Tyler’s exploratory sketches. An independent illustrator produced the final artwork.",
        treatment: "paper",
      },
      {
        src: "/work/teladoc-illustration-tone.webp",
        width: 2048,
        height: 1061,
        alt: "Four kidney-care illustration studies moving from positive to serious emotional tone",
        title: "A consistent style. A sensitive tone.",
        caption:
          "The visual language had to work for both everyday wellness and serious health concerns.",
        treatment: "paper",
        inset: true,
      },
      {
        src: "/work/teladoc-allergy-before.webp",
        width: 2000,
        height: 712,
        alt: "Original allergy cards where severity reads the same at a glance",
        title: "Before.",
        caption: "Severity reads the same.",
        treatment: "edge",
        chapter: "02 / Clearer details, better interactions",
      },
      {
        src: "/work/teladoc-allergy-cards.webp",
        width: 2000,
        height: 778,
        alt: "Three allergy screens with distinct mild, severe, and lethal severity labels",
        title: "After.",
        caption: "Labels and hierarchy you can act on.",
        treatment: "edge",
        inset: true,
      },
      {
        src: "/work/teladoc-loaders.mp4",
        width: 900,
        height: 300,
        alt: "Four loader motion studies for fetching health data",
        title: "Waiting, with a pulse.",
        caption: "Loader studies for every data fetch.",
        treatment: "paper",
        kind: "video",
        poster: "/work/teladoc-loaders-poster.webp",
        loop: true,
      },
      {
        src: "/work/teladoc-illustration-ui-flow.png",
        width: 6156,
        height: 1646,
        alt: "Teladoc onboarding and success screens with spot illustrations in the refreshed OneApp UI",
        title: "Illustration in the new interface.",
        caption:
          "Developing how the spot-illustration system would live in product—from guided onboarding to confirmation moments in the refreshed UI.",
        treatment: "paper",
        inset: true,
      },
      {
        src: "/work/teladoc-launch.mp4",
        width: 374,
        height: 812,
        alt: "Teladoc app launch animation exploration",
        title: "A considered first moment.",
        caption: "An app-launch motion study.",
        treatment: "device",
        kind: "video",
        poster: "/work/teladoc-launch-poster.webp",
        half: true,
        loop: true,
      },
      {
        src: "/work/teladoc-refresh.mp4",
        width: 632,
        height: 1366,
        alt: "Pull-to-refresh animation on the Teladoc health dashboard",
        title: "Make updates feel responsive.",
        caption: "Pull-to-refresh feedback for a dashboard of changing health data.",
        treatment: "device",
        kind: "video",
        poster: "/work/teladoc-refresh-poster.webp",
        half: true,
        loop: true,
      },
      {
        src: "/work/teladoc-care-icons.webp",
        width: 1910,
        height: 491,
        alt: "Medical bag, stethoscope, mental health, and health trend icons",
        title: "Recognizable, even in small spaces.",
        caption: "A graphical icon family carries the brand into everyday product details.",
        treatment: "paper",
        inset: true,
        wash: true,
        chapter: "03 / A scalable visual language",
      },
      {
        src: "/work/teladoc-icon-library.webp",
        width: 1912,
        height: 1168,
        alt: "A 37-icon library for medical, health, and wellness services",
        title: "A system with room to grow.",
        caption: "A shared library for a broad range of care and wellness needs.",
        treatment: "paper",
      },
      {
        src: "/work/teladoc-icon-contrast.webp",
        width: 1950,
        height: 406,
        alt: "Contrast checks for magenta and purple icon colors",
        title: "Test the details.",
        caption: "Contrast checks informed the icon colors and line treatments.",
        treatment: "paper",
        inset: true,
        wash: true,
      },
      {
        src: "/work/teladoc-brand-cards.webp",
        width: 1895,
        height: 548,
        alt: "Three Primary360 service-card explorations",
        title: "Bring the brand into the choice.",
        caption: "Expressive service cards keep the offer and next action clear.",
        treatment: "paper",
        inset: true,
        wash: true,
      },
      {
        src: "/work/teladoc-care-layers.webp",
        width: 2000,
        height: 1840,
        alt: "Layered Teladoc app screens showing the integrated care experience",
        title: "The parts, working together.",
        caption: "Illustration, icons, components, and motion connect the brand to the product.",
        treatment: "composition",
      },
    ],
  },
  {
    slug: "just-for-fun",
    company: "Independent",
    name: "Hand-drawn animation",
    shortName: "Just for Fun",
    headline: "Drawings that move.",
    intro: "I’m an illustrator by heart. These were made just for fun.",
    capabilities: "Illustration · Animation",
    theme: "fun",
    year: "2018–",
    role: "Tyler drew and animated each loop — vector, stop motion, and frame by frame.",
    gallery: [
      {
        src: "/work/fun-01.mp4",
        width: 720,
        height: 720,
        alt: "Hand-drawn animation loop",
        title: "",
        caption: "",
        treatment: "composition",
        kind: "video",
        poster: "/work/fun-01-poster.webp",
        loop: true,
        span: "quarter",
        chapter: "Just for fun. Enjoy!",
      },
      ...([2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const).map((n) => ({
        src: `/work/fun-${String(n).padStart(2, "0")}.mp4`,
        width: 720,
        height: 720,
        alt: "Hand-drawn animation loop",
        title: "",
        caption: "",
        treatment: "composition" as const,
        kind: "video" as const,
        poster: `/work/fun-${String(n).padStart(2, "0")}-poster.webp`,
        loop: true,
        span: "quarter" as const,
      })),
    ],
  },
];

export function publishedProjects() {
  return projects.filter((project) => !project.hidden);
}

export function getProject(slug: string) {
  const project = projects.find((item) => item.slug === slug);
  if (project?.hidden) return undefined;
  return project;
}

export function getNextProject(slug: string) {
  const visible = publishedProjects();
  const index = visible.findIndex((project) => project.slug === slug);
  if (index === -1) return visible[0];
  return visible[(index + 1) % visible.length];
}
